version = 0.1

[default.deploy.parameters]
stack_name = "rsg-invoice-processor"
resolve_s3 = true
s3_prefix = "rsg-invoice-processor"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "FromEmail=\"dreuven@rsgsecurity.com\" ToEmails=\"ar@rsgsecurity.com\" DeployRegion=\"us-east-2\""
image_repositories = []

[default.global.parameters]
region = "us-east-2"
