version = 0.1

[default.deploy.parameters]
stack_name = "rsg-invoice-processor"
resolve_s3 = true
s3_prefix = "rsg-invoice-processor"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "FromEmail=\"dreuven@rsgsecurity.com\" ToEmails=\"ar@rsgsecurity.com\" DeployRegion=\"us-west-1\" ChromiumLayerArn=\"arn:aws:lambda:us-west-1:764866452798:layer:chrome-aws-lambda:63\" LogRetentionInDays=\"90\""
image_repositories = []

[default.global.parameters]
region = "us-west-1"
